export const avatar = {
  wrapper: {
    base: "relative inline-flex items-center justify-center shrink-0 rounded bg-gray-100",
    size: {
      xs: "h-4 w-4",
      sm: "h-5 w-5",
      md: "h-6 w-6",
      lg: "h-7 w-7",
      xl: "h-8 w-8",
      "2xl": "h-10 w-10",
      "3xl": "h-12 w-12",
    },
    circular: "rounded-full",
    border: {
      size: {
        xs: "ring-1.5",
        sm: "ring-1.5",
        md: "ring-1.5",
        lg: "ring-2",
        xl: "ring-2",
        "2xl": "ring-2",
        "3xl": "ring-2",
      },
    },
  },
  icon: {
    base: "inline-flex items-center justify-center text-gray-800",
    size: {
      xs: "text-[0.625rem]",
      sm: "text-[0.625rem]",
      md: "text-xs",
      lg: "text-xs",
      xl: "text-base",
      "2xl": "text-base",
      "3xl": "text-xl",
    },
  },
  initials: {
    base: "text-gray-800 font-medium text-center uppercase",
    size: {
      xs: "text-xs",
      sm: "text-cxs",
      md: "text-sm",
      lg: "text-sm",
      xl: "text-base",
      "2xl": "text-lg",
      "3xl": "text-xl",
    },
  },
  image: {
    base: "rounded w-full h-full object-cover",
    circular: "rounded-full",
  },
  statusIndicator: {
    base: "absolute flex items-center justify-center -bottom-px -right-px",
  },
  statusIndicators: {
    none: {
      base: "",
      size: { xs: "", sm: "", md: "", lg: "", xl: "", "2xl": "" },
    },
    active: {
      base: "text-green-600 ring-1.5 rounded-full",
      size: {
        xs: "text-[4px]",
        sm: "text-[5px]",
        md: "text-[6px]",
        lg: "text-[7px]",
        xl: "text-[8px]",
        "2xl": "text-[10px]",
        "3xl": "text-[12px]",
      },
    },
    sleep: {
      base: "text-gray-600 ring-1.5 rounded-full",
      size: {
        xs: "text-[4px]",
        sm: "text-[5px]",
        md: "text-[6px]",
        lg: "text-[7px]",
        xl: "text-[8px]",
        "2xl": "text-[10px]",
        "3xl": "text-[12px]",
      },
    },
    away: {
      base: "text-gray-600 ring-1.5 rounded-full",
      size: {
        xs: "text-[4px]",
        sm: "text-[5px]",
        md: "text-[6px]",
        lg: "text-[7px]",
        xl: "text-[8px]",
        "2xl": "text-[10px]",
        "3xl": "text-[12px]",
      },
    },
    typing: {
      base: "text-gray-600 ring-1.5 rounded-full",
      size: {
        xs: "w-2",
        sm: "w-[9px]",
        md: "w-[11px]",
        lg: "w-[13px]",
        xl: "w-3.5",
        "2xl": "w-[15px]",
        "3xl": "w-[17px]",
      },
    },
    org: {
      base: "rounded-full",
      size: {
        xs: "text-[6px]",
        sm: "text-[6px]",
        md: "text-[8px]",
        lg: "text-[10px]",
        xl: "text-xs",
        "2xl": "text-sm",
        "3xl": "text-lg",
      },
    },
  },
  group: {
    base: "inline-flex items-center",
    size: {
      xs: "-space-x-px",
      sm: "-space-x-0.5",
      md: "-space-x-0.5",
      lg: "-space-x-0.5",
      xl: "-space-x-1",
      "2xl": "-space-x-1.5",
      "3xl": "-space-x-2",
    },
  },
};
