// Automatically generated
export const TOOLTIP_STATE_KEYS = [
  "baseId",
  "unstable_idCountRef",
  "visible",
  "disclosureRef",
  "popperStyles",
  "arrowStyles",
  "placedSide",
  "placedAlign",
  "side",
  "align",
  "sideOffset",
  "alignOffset",
  "arrowOffset",
  "collisionTolerance",
  "anchor",
  "popper",
  "arrow",
  "unstable_timeout",
  "content",
  "prefix",
  "suffix",
  "withArrow",
  "arrowIcon",
  "setBaseId",
  "show",
  "hide",
  "toggle",
  "setVisible",
  "setSide",
  "setAlign",
  "setSideOffset",
  "setAlignOffset",
  "setArrowOffset",
  "setCollisionTolerance",
  "setAnchor",
  "setPopper",
  "setArrow",
  "unstable_setTimeout",
] as const;
export const USE_TOOLTIP_STATE_KEYS = [
  "baseId",
  "visible",
  "side",
  "align",
  "sideOffset",
  "alignOffset",
  "arrowOffset",
  "collisionTolerance",
  "defaultVisible",
  "onVisibleChange",
  "enableCollisionsDetection",
  "unstable_timeout",
  "content",
  "arrowIcon",
  "withArrow",
  "prefix",
  "suffix",
] as const;
export const TOOLTIP_ANCHOR_KEYS = TOOLTIP_STATE_KEYS;
export const TOOLTIP_ARROW_KEYS = TOOLTIP_ANCHOR_KEYS;
export const TOOLTIP_ARROW_CONTENT_KEYS = TOOLTIP_ARROW_KEYS;
export const TOOLTIP_CONTENT_KEYS = TOOLTIP_ARROW_CONTENT_KEYS;
export const TOOLTIP_REFERENCE_KEYS = TOOLTIP_CONTENT_KEYS;
export const TOOLTIP_TRIGGER_KEYS = TOOLTIP_REFERENCE_KEYS;
export const TOOLTIP_WRAPPER_KEYS = TOOLTIP_TRIGGER_KEYS;
