// Automatically generated
export const USE_CIRCULAR_PROGRESS_STATE_KEYS = [
  "value",
  "min",
  "max",
  "size",
  "hint",
] as const;
export const CIRCULAR_PROGRESS_STATE_KEYS = [
  ...USE_CIRCULAR_PROGRESS_STATE_KEYS,
  "isIndeterminate",
  "percent",
] as const;
export const CIRCULAR_PROGRESS_BAR_KEYS = CIRCULAR_PROGRESS_STATE_KEYS;
export const CIRCULAR_PROGRESS_BAR_WRAPPER_KEYS = CIRCULAR_PROGRESS_BAR_KEYS;
export const CIRCULAR_PROGRESS_HINT_KEYS = CIRCULAR_PROGRESS_BAR_WRAPPER_KEYS;
export const CIRCULAR_PROGRESS_TRACK_KEYS = CIRCULAR_PROGRESS_HINT_KEYS;
export const CIRCULAR_PROGRESS_WRAPPER_KEYS = CIRCULAR_PROGRESS_TRACK_KEYS;
